### ISSUE TITLE
garuda-dr460nized dependencies vs plasma5-themes-sweet-kde-git

### ISSUE THREAD

**Issue by mattie-cmsp** [dr460nf1r3/dr460nixed#40]
Starting today `2023-10-30` is resulting in a an unresolvable dependency chain.

`garuda-dr460nized` depends on `sweet-theme-full-git`

However,
`sweet-theme-full-git` and `sweet-kde-theme-git`
have been replaced by:
`plasma5-themes-sweet-full-git` and `plasma5-themes-sweet-kde-git`

I believe `garuda-dr460nized` simply needs updated to account for the new package themes.

**Comment by dr460nf1r3** [comment]
Hello there! Thanks for making an effort to report this, however, this repository is dedicated to the NixOS builds rather than the Garuda ones. The correct one would be this one here: https://gitlab.com/garuda-linux/themes-and-settings/settings/garuda-dr460nized

Anyway, the needed steps have already been taken! ☺️
